import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './component/NavBar'
const inter = Inter({ subsets: ['latin'] })
import MyProfilePic from './component/MyProfilePic'
export const metadata = {
  title: "Paccy's blog",
  description: 'Generated by me',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-800 bg-red'>

        <NavBar />
        <MyProfilePic />
        {children}
        </body>
    </html>
  )
}
